name: date_picker_timeline_trendway
description: Flutter Date Picker Library that provides a calendar as a horizontal timeline with enabled dates option.
version: 1.0.0
homepage: https://github.com/alexandrebeato/DatePickerTimelineFlutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
