name: ms_date_picker_timeline
description: Flutter Date Picker Library that provides a calendar as a horizontal timeline.
version: 1.0.2
author: Roger Medeiros <rogermedeiros@outlook.com>
homepage: https://github.com/rogermedeirosdasilva/DatePickerTimelineFlutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   fonts:
     - family: Roboto
       fonts:
         - asset: fonts/RobotoRegular.ttf
           weight: 500
         - asset: fonts/RobotoBold.ttf
           weight: 700
