name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      # Setup Dart SDK with JWT token
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f

      - name: Install Flutter & Build App Bundle
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter Packages
        run: flutter pub get

      - name: Publish to pub.dev
        run: flutter pub pub publish -f
